/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "tema.h"

bool_t
xdr_request_info (XDR *xdrs, request_info *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->token_req, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->userid, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->autorefresh))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_request_response (XDR *xdrs, request_response *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->token_req, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->token_access, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->token_refresh, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_validate_info (XDR *xdrs, validate_info *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->token_access, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->op, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->resource, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_validate_response (XDR *xdrs, validate_response *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->token_access, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->token_refresh, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->message, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->ttl))
		 return FALSE;
	return TRUE;
}
